### ISSUE TITLE
Bitrot has taken hold

### ISSUE THREAD

**Issue by TomMD** [jtdaugherty/mathblog#13]
With ghc 7.10.2 and a fresh cabal sandbox, I'm seeing some indication a dependency has changed its API:

```
src/MB/Util.hs:108:36:
    Couldn't match expected type ‘time-1.5.0.1:Data.Time.Format.Locale.TimeLocale’
                with actual type ‘System.Locale.TimeLocale’
    NB: ‘time-1.5.0.1:Data.Time.Format.Locale.TimeLocale’
          is defined in ‘Data.Time.Format.Locale’ in package ‘time-1.5.0.1’
        ‘System.Locale.TimeLocale’
          is defined in ‘System.Locale’ in package ‘old-locale-1.0.0.7’
    In the first argument of ‘parseTime’, namely ‘defaultTimeLocale’
    In the expression: parseTime defaultTimeLocale "%s"

src/MB/Util.hs:115:32:
    Couldn't match expected type ‘Pandoc.Pandoc’
                with actual type ‘Either
                                    Text.Pandoc.Error.PandocError Pandoc.Pandoc’
    In the expression: doc
```

**Comment by jtdaugherty** [comment]
Thanks!  I will look into this today.

**Comment by TomMD** [comment]
See related pull request #14 - which is dumb and bad, but use what you want and then ignore/delete it.

**Comment by jtdaugherty** [comment]
Thank you!  I merged both and also extended your work by using `EitherT` to ensure that the `Left` case of pandoc parsing is well-behaved.  I was already using `EitherT` at the top level anyway, so this made things fit together better.

**Comment by jtdaugherty** [comment]
(I'm assuming I can close this due to having merged both PRs; feel free to re-open if not.)

**Comment by TomMD** [comment]
Perfect, thanks for maintaining!
